export enum RoutePathEnum {
  LOGIN_PATH = 'auth/login',
  RESET_PASS_PATH = 'auth/reset-password',
  TOKEN_REFRESH_PATH = 'token/refresh',

  DASHBOARD_PATH = 'home/dashboard',
  UNAUTHORIZED_PATH = 'auth/unauthorized',

  TRANSACTION_ACTIVITY_PATH = 'transaction_activity/list',
  TRANSACTION_ACTIVITY_STATUS_GET_PATH = 'transaction_status/list',
  ALERT_CASE_ANALYTIC_PATH = 'alert_case_analytic/list',
  TOP_TRIGGERED_RULE_PATH = 'top_rule_triggered/list',

  TRANSACTION_GET_BY_HPAN_PATH = 'transaction/findByHpanCustAcct',
  TRANSACTION_ADDT_GET_BY_HPAN_PATH = 'transaction_addt/findByUtrnno',
  TRANSACTION_GET_TRIGGERED_RULE = 'rule_triggered/findByUtrnno',
  ASSIGN_FRAUD_FLAG = 'transaction/assignFlag',

  USER_GET_PATH = 'user/listUsers',
  USER_GET_FORWARD_PATH = 'user/listForwardUser',
  USER_ADD_PATH = 'user/add',
  USER_UPDATE_PATH = 'user/update',
  USER_DELETE_PATH = 'user/delete',
  USER_RESET_PASS_PATH = 'user/resetpassword',
  USER_GET_QUERY_PATH = 'user/search',

  ROLE_GET_PATH = 'role/list',
  ROLE_ADD_PATH = 'role/add',
  ROLE_UPDATE_PATH = 'role/update',
  ROLE_DELETE_PATH = 'role/delete',
  ROLE_GET_QUERY_PATH = 'role/search',

  OPERATION_GET_PATH = 'operation/list',

  INSTITUTION_GET_PATH = 'institution/list',
  INSTITUTION_ADD_PATH = 'institution/add',
  INSTITUTION_UPDATE_PATH = 'institution/update',
  INSTITUTION_DELETE_PATH = 'institution/delete',
  INSTITUTION_GET_QUERY_PATH = 'institution/search',

  MERCHANT_GET_PATH = 'merchant/list',
  MERCHANT_ADD_PATH = 'merchant/add',
  MERCHANT_UPDATE_PATH = 'merchant/update',
  MERCHANT_DELETE_PATH = 'merchant/delete',
  MERCHANT_GET_QUERY_PATH = 'merchant/search',

  PAN_GET_PATH = 'pan/list',
  PAN_ADD_PATH = 'pan/add',
  PAN_UPDATE_PATH = 'pan/update',
  PAN_DELETE_PATH = 'pan/delete',
  PAN_GET_QUERY_PATH = 'pan/search',

  KEYS_GET_PATH = 'keys/list',
  KEYS_ADD_PATH = 'keys/add',
  KEYS_UPDATE_PATH = 'keys/update',
  KEYS_DELETE_PATH = 'keys/delete',
  KEYS_GET_QUERY_PATH = 'keys/search',

  GROUP_GET_PATH = 'user/group/list',
  GROUP_ADD_PATH = 'user/group/add',
  GROUP_UPDATE_PATH = 'user/group/update',
  GROUP_DELETE_PATH = 'user/group/delete',
  GROUP_GET_QUERY_PATH = 'user/group/search',

  AUDIT_GET_PATH = 'user/audit/list',
  AUDIT_GET_QUERY_PATH = 'user/audit/search',

  ALERT_INVESTIGATION_GET_PATH = 'caseManagement/list',
  ALERT_INVESTIGATION_GET_LOCK_BY_USERNAME_PATH = 'caseManagement/find',
  ALERT_INVESTIGATION_GET_HISTORY_PATH = 'caseHistory/find',
  ALERT_INVESTIGATION_GET_DEMOGRAFI_PATH = 'infoTrans/list',
  ALERT_INVESTIGATION_LOCK_CASE_PATH = 'caseManagement/lockCase',
  ALERT_INVESTIGATION_UNLOCK_CASE_PATH = 'caseManagement/unlockCase',
  ALERT_INVESTIGATION_CLASSIFY_PATH = 'caseManagement/clasify',
  ALERT_INVESTIGATION_TAKE_ACTION_PATH = 'caseManagement/takeAction',
  ALERT_INVESTIGATION_FORWARDED_TO_PATH = 'caseManagement/takeAction/forwardedTo',
  ALERT_INVESTIGATION_QUERY_PATH = 'caseManagement/search',

  WHITE_LIST_GET_PATH = 'whitelist/list',
  WHITE_LIST_ADD_PATH = 'whitelist/addWhitelist',
  WHITE_LIST_UPDATE_PATH = 'whitelist/updateWhitelist',
  WHITE_LIST_DELETE_PATH = 'whitelist/deleteWhitelist',
  WHITE_LIST_GET_QUERY_PATH = 'whitelist/search',
  WHITE_LIST_UPLOAD_PATH = 'whitelist/upload',

  BLACK_LIST_GET_PATH = 'Blacklist/list',
  BLACK_LIST_ADD_PATH = 'Blacklist/addBlacklist',
  BLACK_LIST_UPDATE_PATH = 'Blacklist/updateBlacklist',
  BLACK_LIST_DELETE_PATH = 'Blacklist/deleteBlacklist',
  BLACK_LIST_GET_QUERY_PATH = 'Blacklist/search',
  BLACK_LIST_UPLOAD_PATH = 'Blacklist/upload',

  FRAUD_LIST_GET_PATH = 'sanctionList/list',
  FRAUD_LIST_GET_BY_ENTITY_PATH = 'sanctionList/listByEntityType',
  FRAUD_LIST_ADD_PATH = 'sanctionList/addList',
  FRAUD_LIST_UPDATE_PATH = 'sanctionList/updateList',
  FRAUD_LIST_DELETE_PATH = 'sanctionList/deleteList',
  FRAUD_LIST_GET_QUERY_PATH = 'sanctionList/search',

  FRAUD_LIST_VALUE_ADD_PATH = 'fraudListValue/addValue',
  FRAUD_LIST_VALUE_UPDATE_PATH = 'fraudListValue/updateValue',
  FRAUD_LIST_VALUE_DELETE_PATH = 'fraudListValue/deleteValue',
  FRAUD_LIST_VALUE_GET_BY_ID_PATH = 'fraudListValue/listFraudValueById',
  FRAUD_LIST_VALUE_UPLOAD_PATH = 'fraudListValue/upload',

  FRAUD_REACTIONS_GET_PATH = 'fraudReaction/list',
  FRAUD_REACTIONS_GET_BY_BINDING_PATH = 'fraudReaction/listByBindingIdAndBindingType',
  FRAUD_REACTIONS_ADD_PATH = 'fraudReaction/add',
  FRAUD_REACTIONS_UPDATE_PATH = 'fraudReaction/update',
  FRAUD_REACTIONS_DELETE_PATH = 'fraudReaction/delete',
  FRAUD_REACTIONS_QUERY_PATH = 'fraudReaction/search',

  FRAUD_LIST_TYPE_GET_PATH = 'fraudListType/list',

  TRANS_PARAM_GET_PATH = 'transDataAttr/list',
  TRANS_PARAM_GET_COMMON_PATH = 'transDataAttr/list/common',
  TRANS_PARAM_ADD_PATH = 'transDataAttr/add',
  TRANS_PARAM_UPDATE_PATH = 'transDataAttr/update',
  TRANS_PARAM_DELETE_PATH = 'transDataAttr/delete',
  TRANS_PARAM_GET_QUERY_PATH = 'transDataAttr/search',
  TRANS_PARAM_GET_BY_ENDPOINT_PATH = 'transDataAttr/listByEndpoint',

  TRANS_TYPE_MAPPING_GET_PATH = 'ext_trans_type/list',
  TRANS_TYPE_MAPPING_ADD_PATH = 'ext_trans_type/add',
  TRANS_TYPE_MAPPING_UPDATE_PATH = 'ext_trans_type/update',
  TRANS_TYPE_MAPPING_DELETE_PATH = 'ext_trans_type/delete',
  INT_TRANS_TYPE_GET__PATH = 'trans_type_tab/list',
  TRANS_TYPE_MAPPING_GET_QUERY_PATH = 'ext_trans_type/search',

  AID_PARAMETER_GET_PATH = 'list_aid_label/getAll',
  AID_PARAMETER_ADD_PATH = 'list_aid_label/add',
  AID_PARAMETER_UPDATE_PATH = 'list_aid_label/update',
  AID_PARAMETER_DELETE_PATH = 'list_aid_label/delete',

  RULE_GROUP_GET_PATH = 'ruleGroup/list',
  RULE_GROUP_ADD_PATH = 'ruleGroup/add',
  RULE_GROUP_UPDATE_PATH = 'ruleGroup/update',
  RULE_GROUP_DELETE_PATH = 'ruleGroup/delete',
  RULE_GROUP_GET_QUERY_PATH = 'ruleGroup/search',

  RULE_GET_PATH = 'rule/list',
  RULE_GET_BY_ID_PATH = 'rule/findRuleByRuleId',
  RULE_GET_BY_GROUP_ID_PATH = 'rule/listByGroupId',
  RULE_GET_AGGREGATE_PATH = 'aggregateCounters/list',
  RULE_GET_AGGREGATE_BY_QUERY_PATH = 'aggregateCounters/search',
  RULE_GET_AGGREGATE_BY_ID_PATH = 'aggregateCounters/find',
  RULE_ADD_PATH = 'rule/add',
  RULE_ADD_AGGREGATE_PATH = 'aggregateCounters/add',
  RULE_UPDATE_PATH = 'rule/update',
  RULE_UPDATE_AGGREGATE_PATH = 'aggregateCounters/update',
  RULE_DELETE_PATH = 'rule/delete',
  RULE_ACTIVATION_PATH = 'rule/activation',
  RULE_DEACTIVATION_PATH = 'rule/deactivation',
  RULE_APPROVE_PATH = 'rule/approval',
  RULE_REJECT_PATH = 'rule/rejection',
  RULE_IMPORT_PATH = 'rule/upload',
  RULE_EXPORT_PATH = 'rule/export',
  RULE_PATH = 'home/fraud-management/rule',
  RULE_GET_QUERY_PATH = 'rule/search',

  RULE_HISTORY_GET_BY_ID_PATH = 'rule_history/findByRuleId',

  RESP_CODE_MAPPING_GET_PATH = 'ext_resp_code/list',
  RESP_CODE_MAPPING_ADD_PATH = 'ext_resp_code/add',
  RESP_CODE_MAPPING_DELETE_PATH = 'ext_resp_code/delete',
  RESP_CODE_MAPPING_UPDATE_PATH = 'ext_resp_code/update',
  RESP_CODE_GET_BY_ID_PATH = 'ext_resp_code/listRespById',
  INT_RESP_CODE_GET__PATH = 'resp_tab/list',
  RESP_CODE_MAPPING_GET_QUERY_PATH = 'ext_resp_code/search',

  MSG_CONFIGURATION_ISO8583_GET_PATH = 'msg_configuration/iso8583/list',
  MSG_CONFIGURATION_JSON_GET_PATH = 'msg_configuration/json/list',
  MSG_CONFIGURATION_GET_BY_ID_PATH = 'msg_configuration/find',
  MSG_CONFIGURATION_ADD_PATH = 'msg_configuration/add',
  MSG_CONFIGURATION_UPDATE_PATH = 'msg_configuration/update',
  MSG_CONFIGURATION_DELETE_PATH = 'msg_configuration/delete',
  MSG_CONFIGURATION_ISO8583_GET_QUERY_PATH = 'msg_configuration/iso8583/search',
  MSG_CONFIGURATION_JSON_GET_QUERY_PATH = 'msg_configuration/json/search',

  ENDPOINT_GET_PATH = 'channel_endpoint/list',
  ENDPOINT_GET_BY_ID_PATH = 'channel_endpoint/find',
  ENDPOINT_ADD_PATH = 'channel_endpoint/add',
  ENDPOINT_UPDATE_PATH = 'channel_endpoint/update',
  ENDPOINT_DELETE_PATH = 'channel_endpoint/delete',

  JSON_HEADER_FIELD_GET_PATH = 'json_header_configuration/list',
  JSON_FIELD_ADD_PATH = 'json_header_configuration/add',
  JSON_FIELD_UPDATE_PATH = 'json_header_configuration/update',
  JSON_FIELD_DELETE_PATH = 'json_header_configuration/delete',

  JSON_BODY_FIELD_GET_PATH = 'json_field_configuration/list',
  JSON_BODY_ADD_PATH = 'json_field_configuration/add',
  JSON_BODY_UPDATE_PATH = 'json_field_configuration/update',
  JSON_BODY_DELETE_PATH = 'json_field_configuration/delete',

  FORMATTER_GET_PATH = 'json_field_formatter/list',

  DATA_TYPE_GET_PATH = 'json_field_type/list',

  ACTION_TYPE_GET_PATH = 'json_action_type/list',

  HEADER_FIELD_GET_PATH = 'header_configuration/list',
  HEADER_FIELD_ADD_PATH = 'header_configuration/add',
  HEADER_FIELD_UPDATE_PATH = 'header_configuration/update',
  HEADER_FIELD_DELETE_PATH = 'header_configuration/delete',
  HEADER_FIELD_GET_QUERY_PATH = 'header_configuration/search',

  BODY_FIELD_GET_PATH = 'iso_field_configuration/list',
  BODY_FIELD_ADD_PATH = 'iso_field_configuration/add',
  BODY_FIELD_UPDATE_PATH = 'iso_field_configuration/update',
  BODY_FIELD_DELETE_PATH = 'iso_field_configuration/delete',
  BODY_FIELD_GET_QUERY_PATH = 'iso_field_configuration/search',

  CHILD_BODY_FIELD_GET_PATH = 'iso_subfield_configuration/list',
  CHILD_BODY_FIELD_ADD_PATH = 'iso_subfield_configuration/add',
  CHILD_BODY_FIELD_UPDATE_PATH = 'iso_subfield_configuration/update',
  CHILD_BODY_FIELD_DELETE_PATH = 'iso_subfield_configuration/delete',

  EXT_INT_ISO8583_VIEW_PATH = 'home/ext-interfaces/ISO8583',
  EXT_INT_JSON_VIEW_PATH = 'home/ext-interfaces/JSON',

  NOTIFICATION_TEMPLATE_SETUP_GET_PATH = 'templateSetup/list',
  NOTIFICATION_TEMPLATE_SETUP_ADD_PATH = 'templateSetup/addTemplateSetup',
  NOTIFICATION_TEMPLATE_SETUP_UPDATE_PATH = 'templateSetup/updateTemplateSetup',
  NOTIFICATION_TEMPLATE_SETUP_DELETE_PATH = 'templateSetup/delete',
  NOTIFICATION_TEMPLATE_SETUP_GET_QUERY_PATH = 'templateSetup/search',

  NOTIFICATION_TYPE_GET_PATH = 'notificationType/list',

  NOTIFICATION_RECIPIENT_SETUP_GET_PATH = 'recipientSetup/list',
  NOTIFICATION_RECIPIENT_SETUP_ADD_PATH = 'recipientSetup/addRecipientSetup',
  NOTIFICATION_RECIPIENT_SETUP_UPDATE_PATH = 'recipientSetup/updateRecipientSetup',
  NOTIFICATION_RECIPIENT_SETUP_DELETE_PATH = 'recipientSetup/delete',
  NOTIFICATION_RECIPIENT_SETUP_GET_QUERY_PATH = 'recipientSetup/search',

  NOTIFICATION_RECIPIENT_GROUP_GET_PATH = 'recipientGroup/list',
  NOTIFICATION_RECIPIENT_GROUP_ADD_PATH = 'recipientGroup/addRecipientGroup',
  NOTIFICATION_RECIPIENT_GROUP_UPDATE_PATH = 'recipientGroup/updateRecipientGroup',
  NOTIFICATION_RECIPIENT_GROUP_DELETE_PATH = 'recipientGroup/delete',
  NOTIFICATION_RECIPIENT_GROUP_GET_QUERY_PATH = 'recipientGroup/search',

  USER_NOTIFICATION_GET_PATH = 'userNotification',

  GENERATE_REPORT_PATH = 'report/generate',
  REPORT_GET_PATH = 'jReport/list',
  IMPORT_REPORT_PATH = 'jReport/import',
  EXPORT_REPORT_PATH = 'jReport/export',
  REPORT_DELETE_PATH = 'jReport/delete',
}
